let cookies = [
    {
        "domain": ".keylol.com",
        "expirationDate": 1682857173.936105,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__yjs_duid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1_a0718c6fc38219c6db0b129729002fca1619785172829",
        "id": 1
    },
    {
        "domain": ".keylol.com",
        "expirationDate": 1704679391,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.2088565791.1637656650",
        "id": 2
    },
    {
        "domain": ".keylol.com",
        "expirationDate": 1641607451,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gat_gtag_UA_17880378_3",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 3
    },
    {
        "domain": ".keylol.com",
        "expirationDate": 1641693791,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.2.223154370.1638945067",
        "id": 4
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1642047383.54316,
        "hostOnly": true,
        "httpOnly": true,
        "name": "dz_2132_auth",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "b6fd%2BEaoTs8SHiqwds3CM5vTJQO9H6IDkHz4DzBZ%2FhlsT%2FmylYfvRATPf53GZeuztdrJmvX8t3zrABekmKAD83ugA6M",
        "id": 5
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1641607421.79349,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_checkpm",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 6
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1643343383.543124,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_client_created",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1640751383",
        "id": 7
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1643343383.543136,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_client_token",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "DF2D1539FC7AEAEE1D03D7861DE63DEB",
        "id": 8
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1673143392.351221,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_connect_is_bind",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 9
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1642047383.54319,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_connect_login",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 10
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1672287383.543212,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_connect_uin",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "DF2D1539FC7AEAEE1D03D7861DE63DEB",
        "id": 11
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1641693792.351239,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_duceapp_sid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "nCGgww",
        "id": 12
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1642123535.043495,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_forum_lastvisit",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "D_274_1639624383D_335_1640396870D_316_1640511621D_271_1641259279D_148_1641518619D_201_1641518712D_343_1641518723D_313_1641518739",
        "id": 13
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1641693792.35115,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_lastact",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1641607394%09plugin.php%09",
        "id": 14
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1670917285.948202,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_lastcheckfeed",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "308427%7C1639381285",
        "id": 15
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1641973278.787646,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_lastvisit",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1639377678",
        "id": 16
    },
    {
        "domain": "keylol.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_lip",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": true,
        "storeId": "0",
        "value": "123.147.248.111%2C1641606896",
        "id": 17
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1641973278.787604,
        "hostOnly": true,
        "httpOnly": true,
        "name": "dz_2132_saltkey",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "HOjwjKV2",
        "id": 18
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1641607692.332984,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_sendmail",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 19
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1641693791.268036,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_sid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "pwFe1m",
        "id": 20
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1673077905,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_smile",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "4D1",
        "id": 21
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1673143085.39435,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_ulastactivity",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "7c1btVZLPqi4Vll4LCSM3EsCfOC3FsNIMRAD2HNPxRj84LyE94UB",
        "id": 22
    },
    {
        "domain": "keylol.com",
        "expirationDate": 1644133793.175507,
        "hostOnly": true,
        "httpOnly": false,
        "name": "dz_2132_visitedfid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "148D313D343D201D234D302D161D330D271D319",
        "id": 23
    }
]

let res = "";
for (const cookie of cookies) {
    res += `${cookie.name}:${cookie.value}; `
}
console.log(res);